import * as icon from 'react-icons/si'

const profile = {
	name: 'Kai Xia',
	role: 'Software Developer',
	description: 'Your curiosity leads you here to know more about me, let\'s find out !',
};

const social = [
	{ icon: icon.SiLinkedin, link: 'https://www.linkedin.com/in/kaixia-ca/' },
	{ icon: icon.SiGithub, link: 'https://github.com/Monbert' },
	// { icon: icon.SiTwitter, link: 'https://www.twitter.com/' },
	// { icon: icon.SiInstagram, link: 'https://www.instagram.com/' },
];

const brand = 'KAIZEN'


const work = [
	{
		name: 'RBC Challenges',
		description: ' A prototype of customer feedback analysis for RBC. The project includes twitter data collection, sentiment analysis and PHP front-page display.',
		stack: [
			{ icon: icon.SiPython, name: 'Python' },
			{ icon: icon.SiMysql, name: 'Mysql' },
			{ icon: icon.SiJavascript, name: 'Javascript' },
			{ icon: icon.SiHtml5, name: 'HTML' },
			{ icon: icon.SiCss3, name: 'CSS' },
			{ icon: icon.SiTwitter, name: 'Twitter' },

		],
		linkProject: 'https://devpost.com/software/rbc-challenges-twitter-customer-feedback-analysis',
		linkGithub: 'https://github.com/lancepokaiwang/CUHacking2020',
	},
	{
		name: 'Sensor Fusion',
		description: 'The software can calculate a single and weighted value from many sensor\'s values. And the value generated by the algorithm is representative of the correct raw data.',
		stack: [
			{ icon: icon.SiC, name: 'C' },
			{ icon: icon.SiGnu, name: 'GNU' },
			{ icon: icon.SiGit, name: 'Git' },
			{ icon: icon.SiCmake, name: 'Cmake' },
		],
		linkProject: 'https://github.com/Monbert/sensorFusion_Demo',
		linkGithub: 'https://github.com/Monbert/sensorFusion_Demo',
	},
	{
		name: 'People Catalog',
		description: 'IOS app for managing and displaying catalogue of employees and their all skills, also it can edit skills.',
		stack: [
			{ icon: icon.SiReact, name: 'ReactJS' },
			{ icon: icon.SiJavascript, name: 'Javascript' },
			{ icon: icon.SiHtml5, name: 'HTML' },
			{ icon: icon.SiCss3, name: 'CSS' },
			{ icon: icon.SiPython, name: 'Python' },
			{ icon: icon.SiPostgresql, name: 'Postgresql' },
			{ icon: icon.SiAzurefunctions, name: 'AzureFunctions' },


		],
		// linkProject: 'https://example.com',
		// linkGithub: 'https://github.com',
	},
	// {
	// 	name: 'Twitter clon',
	// 	description: 'Cras leo mauris, gravida vel lectus ac, congue luctus odio. Sed varius varius est eget convallis sagittis sit amet.',
	// 	stack: [
	// 		{ icon: icon.SiHtml5, name: 'HTML' },
	// 		{ icon: icon.SiCss3, name: 'CSS' },
	// 		{ icon: icon.SiJavascript, name: 'Javascript' },
	// 		{ icon: icon.SiReact, name: 'ReactJS' },
	// 	],
	// 	linkProject: 'https://example.com',
	// 	linkGithub: 'https://github.com',
	// },
]


const stack = [
	{
		name: 'Programming Languages',
		items: [
			{ icon: icon.SiJava, name: 'Java' },
			{ icon: icon.SiPython, name: 'Python' },
			{ icon: icon.SiC, name: 'C' },
			{ icon: icon.SiCsharp, name: 'C#' },

		],
	},
	{
		name: 'Front End',
		items: [
			{ icon: icon.SiJavascript, name: 'Javascript' },
			{ icon: icon.SiTypescript, name: 'Typescript' },
			{ icon: icon.SiHtml5, name: 'HTML' },
			{ icon: icon.SiCss3, name: 'CSS' },
			{ icon: icon.SiReact, name: 'React', },
			{ icon: icon.SiBootstrap, name: 'Bootstrap', },
			{ icon: icon.SiAngularjs, name: 'AngularJS', },

		],
	},
	{
		name: 'Back End',
		items: [
			{ icon: icon.SiMysql, name: 'Mysql' },
			{ icon: icon.SiPostgresql, name: 'Postgresql' },
			{ icon: icon.SiMicrosoftsqlserver, name: 'Microsoft-sqlServer' },
			{ icon: icon.SiAzurefunctions, name: 'AzureFunctions' },
			{ icon: icon.SiSpringboot, name: 'Springboot', },
			{ icon: icon.SiAmazonaws, name: 'AWS', },
		],
	},
]

const contact = {
	description: 'Feel free to contact me for any work or suggestions below ',
	email: 'kaixia0815@outlook.com'
}

export { profile, social, work, stack, contact, brand }